version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      build:
        docker:
          - image: circleci/openjdk:11-browser-legacy
        working_directory: ~/repo

        environment:
          MAVEN_OPTS: -Xmx3200m

        steps:
          - checkout
          - restore cache:
              keys:
                - v1-dependencies={{ checksum "pom.xml" }}
                - v1-dependencies-
          - run: mvn dependency:go-offline
          - save_cache:
              paths:
                - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}
          - run: mvn integration-test